vl_auth_client:
    oauth:
        client_id: '%oauth_client_id%'
        client_secret: '%oauth_client_secret%'
        authserver: '%oauth_client_server%'
        scope: 'profile:realname profile:groups property:read property:write'
    user_provider:
        entity: AppBundle:User
    listeners:
        locale: ~

hwi_oauth:
    firewall_names: [ main ]
