security:
    encoders:
        AppBundle\Entity\ApiUser: plaintext

    role_hierarchy:
        ROLE_GROUP_%SYSOPS: ROLE_ADMIN
        ROLE_ADMIN: ROLE_USER


    providers:
        api:
            entity:
                class: AppBundle:ApiUser
                property: username
        main:
            id: vl_auth_client.user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            provider: api
            pattern: ^/api
            stateless: true
            http_basic: ~

        main:
            pattern: ^/
            provider: main
            oauth:
                resource_owners:
                    vl_auth_client: /login/oauth
                login_path: /login
                use_forward: false
                failure_path: /login
                oauth_user_provider:
                    service: vl_auth_client.user_provider
            logout:
                target: '%oauth_client_server%/usr/kill-session'
            anonymous: ~
    access_control:
        - { path: ^/login_check, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: ROLE_API }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
