api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api

login:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: hwi_oauth_service_redirect
        service: vl_auth_client

hwi_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

login_check:
    path: /login_check

logout:
    path: /logout

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    type: rest

