admin_apiuser:
    resource: '@AppBundle/Controller/Admin/ApiUserController.php'
    name_prefix: admin_
    type: rest
    requirements:
        user: '[0-9]+'

admin_queuedmessage:
    resource: '@AppBundle/Controller/Admin/QueuedMessageController.php'
    name_prefix: admin_
    type: rest
    requirements:
        message: '[0-9]+'


vl_acl:
    resource: "@VlAclBundle/Resources/config/routing.yml"
