admin_apiuser:
    resource: '@AppBundle/Controller/Admin/ApiUserController.php'
    name_prefix: admin_
    type: rest
    requirements:
      user: '[0-9]+'


vl_acl:
    resource: "@VlAclBundle/Resources/config/routing.yml"
