admin_apiuser:
    resource: '@AppBundle/Controller/Admin/ApiUserController.php'
    name_prefix: admin_
    type: rest

admin_emailaddress:
    resource: '@AppBundle/Controller/Admin/EmailAddressController.php'
    name_prefix: admin_
    type: rest

vl_acl:
    resource: "@VlAclBundle/Resources/config/routing.yml"
