admin:
    resource: routing/admin.yml
    type: rest
    prefix: /admin

emailaddress:
    resource: '@AppBundle/Controller/EmailAddressController.php'
    type: rest

emailtemplate:
    resource: '@AppBundle/Controller/EmailTemplateController.php'
    type: rest

localized_emailtemplate:
    resource: '@AppBundle/Controller/LocalizedEmailTemplateController.php'
    parent: emailtemplate
    type: rest

emailtransport:
    resource: '@AppBundle/Controller/EmailTransportController.php'
    type: rest

home:
    path: /
    defaults:
        _format: ~