- hosts: localhost
  tasks:
    - name: Create directory structure
      file: path=/var/www/{{ item }} recurse=yes state=directory
      with_items:
        - var/cache
        - var/logs
        - var/sessions
        - web
    - name: Copy static files
      command: cp -r /vagrant/{{ item }} /var/www/{{ item|dirname }}
      with_items:
        - app
        - bin
        - web/.htaccess
        - web/app_dev.php
        - composer.json
        - composer.lock
        - package.json
    - name: Start mysql
      service: name=mysql state=started
    - name: Create mysql user
      mysql_user: name=hermes password=hermes priv=*.*:ALL state=present
    - name: Create mysql database
      mysql_db: name=hermes state=present
    - name: Generate random secret
      shell: base64 < /dev/urandom | head -1
      register: random
    - name: Create app/config/parameters.yml
      template: src=parameters.yml.j2 dest=/var/www/app/config/parameters.yml
    - name: composer install
      composer: working_dir=/var/www no_dev=no
    - name: npm install
      npm: path=/var/www
    - name: Clear cache, install assets and migrate database
      command: php bin/console {{ item }} -n chdir=/var/www
      with_items:
        - cache:clear
        - assets:install
        - braincrafted:bootstrap:install
        - assetic:dump
        - doctrine:migrations:migrate
    - name: Make cache & logs writeable by webserver
      file: path=/var/www/{{ item }} owner=www-data mode=0777 recurse=yes state=directory
      with_items:
        - var
        - var/cache
        - var/sessions
        - var/logs
    - name: Configure apache to use development environment
      command: sed s/app/app_dev/ -i /var/www/web/.htaccess
    - name: Remove restrictions on web/app_dev.php
      command: 'sed -e "/production servers/,+9d" -i /var/www/web/app_dev.php'
    - name: Remove HTTPS redirection
      command: 'sed -e "/Redirect to HTTPS/,+3d" -i /var/www/web/.htaccess'
    - name: "
    Some helpful information.\n
    Webserver running at http://192.168.80.9/\n
    \n
    Run 'vagrant provision' when you update files outside src/\n
    \n
    "
      service: name=apache2 state=started
